#e : words_app.beam
e :
	time escript words.escript ~/Dropbox/words wood
	time escript words.escript ~/Dropbox/words was
	time escript words.escript ~/Dropbox/words army
	time escript words.escript ~/Dropbox/words Mary

words_app.beam : words_app.erl
	erlc -W $<


