FROM fedora

RUN dnf -y install composer

RUN dnf -y install \
    procps-ng \
    psmisc \
    screen \
    tmux \
    time \
    make \
    vim \
    git

RUN dnf -y install \
  php-pecl-yaml \
  php-mysqlnd \
  php-mcrypt
